# Generated by Django 4.1.3 on 2022-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='trainer_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment'),
        ),
    ]
